<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_agenda  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeDelete"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$idm = $values["group_agenda_id"];
if($values['loop_id'] == 2)
{
  $data = array();
  $keyvalues = array();
  $data["loop_value"] = NOW();
  $keyvalues["group_agenda_id"] = $values["group_agenda_id"];
  DB::Update("group_agenda", $data , $keyvalues);
}
//**********  Insert a record into another table  ************


// Place event code here.
// Use "Add Action" button to add code snippets.


// Place event code here.
// Use "Add Action" button to add code snippets.

if($values["message_general"] == "General")
{
  $data = array();
  $data["group_id"] = $values[group_id];
  $rs = DB::Select("group_member", $data );

  while( $record = $rs->fetchAssoc() )
  {
    $mmid = $record["member_id"];
    $gmid = $record["group_member_id"];
    $agendaType = $values["agenda_type_id"];
    $rs1 = DB::Query("select member_id from group_member_agenda_subscriber
    where agenda_type_id = '$agendaType' AND member_id = '$mmid'");
    $dataAgendaType = $rs1->fetchAssoc();
    if($dataAgendaType)
    {
      $data2 = array();
      $data2["group_member_id"] = $gmid;
      $data2["member_id"] = $mmid;
      $data2["group_agenda_id"] = $values['group_agenda_id'];
      DB::Insert("group_member_agenda", $data2 );
      $tgl = $values["loop_value"];
      $repeat = $values["repeat"];
      if($repeat == 0 || $repeat == null)
      {
        
        $data4 = array();
        $data4["member_id"] = $mmid;
        $data4["id_group_agenda"] = $values["group_agenda_id"];
        $data4["date_send"] = $values['loop_value'];
        DB::Insert("group_agenda_general_logs", $data4 );

        $data3 = array();
        $data3["out_msg"] = $values["message_content"];
        $data3["type"] = "msg";
        $data3["flag"] = 1;
        $data3["group_member_id"] = $gmid;
        $data3["member_id"] = $mmid;
        $data3["group_id"] = $values["group_id"];
        $data3["group_agenda_id"] = $values["group_agenda_id"];

        $data31 = array();
        $data31["out_msg"] = $values['attachment'];
        $data31["type"] = "file";
        $data31["flag"] = 1;
        $data31["group_member_id"] = $gmid;
        $data31["member_id"] = $mmid;
        $data31["group_id"] = $values["group_id"];
        $data31["group_agenda_id"] = $values["group_agenda_id"];

				 if($values['loop_id'] == '2')
					{
						$data3["tgl"] = NOW();
						$data31["tgl"] = NOW();
					}
					else 
					{
						$data3["tgl"] = $tgl;
						$data31["tgl"] = $tgl;
					}

        $rs2 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 1");
        $dataChannelTele=$rs2->fetchAssoc();
        if($dataChannelTele)
        {
          $data3["chat_id"] = $dataChannelTele["chat_id"];
          $data31["chat_id"] = $dataChannelTele["chat_id"];
          DB::Insert("outbox_telegram", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_telegram", $data31 );
						}

        }

        $rs3 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 2");
        $dataChannelAws=$rs3->fetchAssoc();
        if($dataChannelAws)
        {
          $data3["chat_id"] = $dataChannelAws["chat_id"];
          $data31["chat_id"] = $dataChannelAws["chat_id"];
          DB::Insert("outbox_mail_aws", $data3 );
          DB::Insert("outbox_mail_alibaba", $data3 );
          DB::Insert("outbox_mail_mailchimp", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_mail_aws", $data31 );
							DB::Insert("outbox_mail_alibaba", $data31 );
							DB::Insert("outbox_mail_mailchimp", $data31 );
						}
		
        }

        $rs4 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 3");
        $dataChannelWa=$rs4->fetchAssoc();
        if($dataChannelWa)
        {
          $data3["chat_id"] = $dataChannelWa["chat_id"];
          $data31["chat_id"] = $dataChannelWa["chat_id"];
          DB::Insert("outbox_whatsapp", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_whatsapp", $data31 );
						}
        }


        $rs5 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 4");
        $dataChannelLine=$rs5->fetchAssoc();
        if($dataChannelLine)
        {
          $data3["chat_id"] = $dataChannelLine["chat_id"];
          $data31["chat_id"] = $dataChannelLine["chat_id"];
          DB::Insert("outbox_line", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_line", $data31 );
						}
        }
      }
      else
      {
        $data3 = array();
        $i = 0;
        while($i <= $repeat)
	      {
          $rep = $values["repeat_type"];
          if($rep == "bydate")
          {
						$data1 = array();
						$data1["out_msg"] = $values["message_content"];
						$data1["type"] = "msg";
						$data1["flag"] = 1;
					  $data1["group_member_id"] = $gmid;
					  $data1["member_id"] = $mmid;
					  $data1["group_id"] = $values["group_id"];
					  $data1["group_agenda_id"] = $values["group_agenda_id"];

						$data11 = array();
						$data11["out_msg"] = $values["attachment"];
						$data11["type"] = "file";
						$data11["flag"] = 1;
					  $data11["group_member_id"] = $gmid;
					  $data11["member_id"] = $mmid;
					  $data11["group_id"] = $values["group_id"];
					  $data11["group_agenda_id"] = $values["group_agenda_id"];

						$data2 = array();
						$data4 = array();
						$data4["member_id"] = $mmid;
						$data4["id_group_agenda"] = $values["group_agenda_id"];
						$data4["date_send"] = $tgl;
            if($i == 0)
            {
              
              $data1["tgl"] = $tgl;
              $data11["tgl"] = $tgl;
              $rs1 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 1");
              $dataChannelTele=$rs1->fetchAssoc();
              if($dataChannelTele)
              {
               $data1["chat_id"] = $dataChannelTele["chat_id"];
               $data11["chat_id"] = $dataChannelTele["chat_id"];
               DB::Insert("outbox_telegram", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_telegram", $data11 );
								}
              }
      
              $rs2 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 2");
              $dataChannelAws=$rs2->fetchAssoc();
              if($dataChannelAws)
              {
               $data1["chat_id"] = $dataChannelAws["chat_id"];
               $data11["chat_id"] = $dataChannelAws["chat_id"];
               DB::Insert("outbox_mail_alibaba", $data1 );
               DB::Insert("outbox_mail_aws", $data1 );
               DB::Insert("outbox_mail_mailchimp", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_mail_alibaba", $data11 );
									DB::Insert("outbox_mail_aws", $data11 );
									DB::Insert("outbox_mail_mailchimp", $data11 );
								}
              }
      
              $rs3 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 3");
              $dataChannelWa=$rs3->fetchAssoc();
              if($dataChannelWa)
              {
               $data1["chat_id"] = $dataChannelWa["chat_id"];
               $data11["chat_id"] = $dataChannelWa["chat_id"];
               DB::Insert("outbox_whatsapp", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_whatsapp", $data11 );
								}
              }
      
              $rs4 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 4");
              $dataChannelLine=$rs4->fetchAssoc();
              if($dataChannelLine)
              {
               $data1["chat_id"] = $dataChannelLine["chat_id"];
               $data11["chat_id"] = $dataChannelLine["chat_id"];
               DB::Insert("outbox_line", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_line", $data11 );
								}
              }


								DB::Insert("group_agenda_general_logs", $data4 );
            }
            else
            {
              //$data2["group_agenda_id"] = $idm;
              //$data2["dodate"] = now();
              //DB::Insert("group_agenda_repeat_date", $data2 );
								//DB::Insert("group_agenda_general_logs", $data4 );
            }
          }
          else
          {
            if($i == 0)
            {
              $data3["tgl"] = $tgl;
              $data31["tgl"] = $tgl;
								$tgl3 = $tgl;
            }else if($i > 0)
            {
              
              if($values["repeat_type"] == "daily")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 day' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "weekly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 week' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "monthly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 month' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "yearly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 year' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }
            }
            $data4 = array();
            $data4["member_id"] = $mmid;
            $data4["id_group_agenda"] = $values["group_agenda_id"];
            $data4["date_send"] = $tgl3;
            DB::Insert("group_agenda_general_logs", $data4 );
            
            
            $data3["out_msg"] = $values["message_content"];
            $data3["type"] = "msg";
            $data3["flag"] = 1;
					  $data3["group_member_id"] = $gmid;
					  $data3["member_id"] = $mmid;
					  $data3["group_id"] = $values["group_id"];
					  $data3["group_agenda_id"] = $values["group_agenda_id"];

            $data31["out_msg"] = $values["attachment"];
            $data31["type"] = "file";
            $data31["flag"] = 1;
					  $data31["group_member_id"] = $gmid;
					  $data31["member_id"] = $mmid;
					  $data31["group_id"] = $values["group_id"];
					  $data31["group_agenda_id"] = $values["group_agenda_id"];

            $rs2 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 1");
            $dataChannelTele=$rs2->fetchAssoc();
            if($dataChannelTele)
            {
              $data3["chat_id"] = $dataChannelTele["chat_id"];
              $data31["chat_id"] = $dataChannelTele["chat_id"];
              DB::Insert("outbox_telegram", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_telegram", $data31 );
								}

            }

            $rs3 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 2");
            $dataChannelAws=$rs3->fetchAssoc();
            if($dataChannelAws)
            {
              $data3["chat_id"] = $dataChannelAws["chat_id"];
              $data31["chat_id"] = $dataChannelAws["chat_id"];
              DB::Insert("outbox_mail_alibaba", $data3 );
              DB::Insert("outbox_mail_aws", $data3 );
              DB::Insert("outbox_mail_mailchimp", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_mail_alibaba", $data31 );
									DB::Insert("outbox_mail_aws", $data31 );
									DB::Insert("outbox_mail_mailchimp", $data31 );
								}
            }

            $rs4 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 3");
            $dataChannelWa=$rs4->fetchAssoc();
            if($dataChannelWa)
            {
              $data3["chat_id"] = $dataChannelWa["chat_id"];
              $data31["chat_id"] = $dataChannelWa["chat_id"];
              DB::Insert("outbox_whatsapp", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_whatsapp", $data31 );
								}
            }


            $rs5 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 4");
            $dataChannelLine=$rs5->fetchAssoc();
            if($dataChannelLine)
            {
              $data3["chat_id"] = $dataChannelLine["chat_id"];
              $data31["chat_id"] = $dataChannelLine["chat_id"];
              DB::Insert("outbox_line", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_line", $data31 );
								}
            }

          }
					$i += 1;
        }
      }
    }
  }
}
/*else if ($values["message_general"] == "Private")
{
 $data = array();
 $data["group_id"] = $values[group_id];
 $rs = DB::Select("group_member", $data );

 while( $record = $rs->fetchAssoc() )
 {
  $mmid = $record["member_id"];
  $gmid = $record["group_member_id"];
  $agendaType = $values["agenda_type_id"];
  $rs1 = DB::Query("select member_id from group_member_agenda_subscriber
  where agenda_type_id = '$agendaType' AND member_id = '$mmid'");
  $dataAgendaType = $rs1->fetchAssoc();
  if($dataAgendaType)
  {
	$data1 = array();
	$data1["group_member_id"] = $gmid;
	$data1["member_id"] = $mmid;
	$data1["group_agenda_id"] = $values['group_agenda_id'];
	DB::Insert("group_member_agenda", $data1 );
	
  $data2 = array();
  $data2["id_group_agenda"] = $values['group_agenda_id'];
  $data2["id_member"] = $mmid;
  $data2["message_content"] = $values["message_content"];
  $data2["attachment"] = $values["attachment"];
  $data2["date_send"] = $values["send_date"];
  DB::Insert("group_agenda_private", $data2 );

  $data3 = array();
    $data3["out_msg"] = $values["message_content"];
    $data3["type"] = "msg";
    $data3["flag"] = 1;
    $data3["tgl"] = $values["send_date"];

   $rs2 = DB::Query("select chat_id from personal_channel
   where member_id = '$mmid' AND channel_id = 1");
   $dataChannelTele=$rs2->fetchAssoc();
   if($dataChannelTele)
   {
    $data3["chat_id"] = $dataChannelTele["chat_id"];
    DB::Insert("outbox_telegram", $data3 );

   }

   $rs3 = DB::Query("select chat_id from personal_channel
   where member_id = '$mmid' AND channel_id = 2");
   $dataChannelAws=$rs3->fetchAssoc();
   if($dataChannelAws)
   {
    $data3["chat_id"] = $dataChannelAws["chat_id"];
    DB::Insert("outbox_mail_aws", $data3 );
   }

   $rs4 = DB::Query("select chat_id from personal_channel
   where member_id = '$mmid' AND channel_id = 3");
   $dataChannelWa=$rs4->fetchAssoc();
   if($dataChannelWa)
   {
    $data3["chat_id"] = $dataChannelWa["chat_id"];
    DB::Insert("outbox_whatsapp", $data3 );
   }

   $rs5 = DB::Query("select chat_id from personal_channel
   where member_id = '$mmid' AND channel_id = 4");
   $dataChannelLine=$rs5->fetchAssoc();
   if($dataChannelLine)
   {
    $data3["chat_id"] = $dataChannelLine["chat_id"];
    DB::Insert("outbox_line", $data3 );
   }

  
  }
 }
}
*/

if($values['message_general']=='Private'){
	header("Location: group_agenda_private_import.php");
	exit();
}

if($values['repeat_type']!='bydate'){
	header("Location: group_agenda_list.php");
	exit();
}

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, &$pageObject)
{

		$pageObject->hideField("agenda_name");
$pageObject->hideField("group_id");
$pageObject->hideField("agenda_type_id");
$pageObject->hideField("message_content");
$pageObject->hideField("attachment");
$pageObject->hideField("loop_id");
$pageObject->hideField("loop_value");
$pageObject->hideField("loop_id");
$pageObject->hideField("repeat");
$pageObject->hideField("repeat_type");
$pageObject->hideField("send_date");
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, &$pageObject)
{

		$data = array();
$data["group_agenda_id"] = $deleted_values['group_agenda_id'];
$data["flag"] = '1';

DB::Delete("outbox_mail_alibaba", $data );
DB::Delete("outbox_mail_aws", $data );
DB::Delete("outbox_mail_mailchimp", $data );
DB::Delete("outbox_telegram", $data );
DB::Delete("outbox_whatsapp", $data );
DB::Delete("outbox_line", $data );

$data = array();
$keyvalues = array();
$data["group_agenda_id"] = null;
$keyvalues["group_agenda_id"] = $deleted_values['group_agenda_id'];

DB::Update("outbox_mail_alibaba", $data, $keyvalues );
DB::Update("outbox_mail_aws", $data, $keyvalues );
DB::Update("outbox_mail_mailchimp", $data, $keyvalues );
DB::Update("outbox_telegram", $data, $keyvalues );
DB::Update("outbox_whatsapp", $data, $keyvalues );
DB::Update("outbox_line", $data, $keyvalues );

$data = array();
$data["group_agenda_id"] = $deleted_values['group_agenda_id'];

$data1 = array();
$data1["id_group_agenda"] = $deleted_values['group_agenda_id'];

DB::Delete("group_agenda_general_logs", $data1 );
DB::Delete("group_agenda_private", $data1 );
DB::Delete("group_member_agenda", $data );
DB::Delete("group_agenda_repeat_date", $data );

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, &$pageObject)
{

		$pageObject->hideField("loop_type");
$pageObject->hideField("message_content");
$pageObject->hideField("attachment");
$pageObject->hideField("repeat");
$pageObject->hideField("repeat_type");
$pageObject->hideField("loop_value");
$pageObject->hideField("agenda_type_id");
$pageObject->hideField("agenda_name");
$pageObject->hideField("send_date");
$pageObject->hideField("group_id");

if($values['message_general'] == 'General'){
	if($values['loop_id'] == '1'){	
		$data = array();
		$data["group_agenda_id"] = $values['group_agenda_id'];
		$data["flag"] = '2';
		$rs = DB::Select("outbox_line", $data );
		$rs1 = DB::Select("outbox_mail_alibaba", $data );
		$rs2 = DB::Select("outbox_mail_aws", $data );
		$rs3 = DB::Select("outbox_mail_mailchimp", $data );
		$rs4 = DB::Select("outbox_telegram", $data );
		$rs5 = DB::Select("outbox_whatsapp", $data );

		$i = 1;
		while( $record = $rs->fetchAssoc() )
		{
				$i = 2;
		}
		while( $record = $rs1->fetchAssoc() )
		{
				$i = 2;
		}
		while( $record = $rs2->fetchAssoc() )
		{
				$i = 2;
		}
		while( $record = $rs3->fetchAssoc() )
		{
				$i = 2;
		}
		while( $record = $rs4->fetchAssoc() )
		{
				$i = 2;
		}
		while( $record = $rs5->fetchAssoc() )
		{
				$i = 2;
		}

		if($i == 2){
			if($values['repeat'] > 0){
				$pageObject->showField("message_content");
				$pageObject->showField("attachment");

				$data2 = array();
				$data2["group_agenda_id"] = $values['group_agenda_id'];
				$rsa = DB::Select("outbox_line", $data2 );
				$rs1a = DB::Select("outbox_mail_alibaba", $data2 );
				$rs2a = DB::Select("outbox_mail_aws", $data2 );
				$rs3a = DB::Select("outbox_mail_mailchimp", $data2 );
				$rs4a = DB::Select("outbox_telegram", $data2 );
				$rs5a = DB::Select("outbox_whatsapp", $data2 );

				$data1 = array();
				$data1["group_agenda_id"] = $values['group_agenda_id'];
				$data1["flag"] = '1';
				$rs = DB::Select("outbox_line", $data1 );
				$rs1 = DB::Select("outbox_mail_alibaba", $data1 );
				$rs2 = DB::Select("outbox_mail_aws", $data1 );
				$rs3 = DB::Select("outbox_mail_mailchimp", $data1 );
				$rs4 = DB::Select("outbox_telegram", $data1 );
				$rs5 = DB::Select("outbox_whatsapp", $data1 );
				
				$a = 0;
				$b = 0;
				$c = 0;
				$d = 0;
				$e = 0;
				$f = 0;
				if($rsa->fetchAssoc()){
					if($rs->fetchAssoc()){
						$a = 1;
					}
				}else{
					$a = 1;
				}
				
				if($rs1a->fetchAssoc()){
					if($rs1->fetchAssoc()){
						$b = 1;
					}
				}else{
					$b = 1;
				}

				if($rs2a->fetchAssoc()){
					if($rs2->fetchAssoc()){
						$c = 1;
					}
				}else{
					$c = 1;
				}

				if($rs3a->fetchAssoc()){
					if($rs3->fetchAssoc()){
						$d = 1;
					}
				}else{
					$d = 1;
				}

				if($rs4a->fetchAssoc()){
					if($rs4->fetchAssoc()){
						$e = 1;
					}
				}else{
					$e = 1;
				}

				if($rs5a->fetchAssoc()){
					if($rs5->fetchAssoc()){
						$f = 1;
					}
				}else{
					$f = 1;
				}

				if($a == 0 || $b == 0 || $c == 0 || $d == 0 || $e == 0 || $f == 0){
					$pageObject->hideField("message_content");
					$pageObject->hideField("attachment");
				}
			}
		}else{
			$pageObject->showField("loop_value");
			$pageObject->showField("message_content");
			$pageObject->showField("attachment");
			if($values['repeat'] > 0){
				$pageObject->showField("repeat");
				$pageObject->showField("repeat_type");
			}
		}
	}
}else{
$pageObject->showField("agenda_name");
$pageObject->showField("send_date");
$pageObject->showField("attachment");
}
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		if($values['loop_id'] == '1' && $oldvalues['repeat'] != '0' && ($values['repeat'] != $oldvalues['repeat'] || $values['repeat_type'] != $oldvalues['repeat_type']  || $values['loop_value'] != $oldvalues['loop_value'])){

	$datax = array();
	$datax["group_agenda_id"] = $values['group_agenda_id'];
	DB::Delete("outbox_line", $datax );
	DB::Delete("outbox_mail_alibaba", $datax );
	DB::Delete("outbox_mail_aws", $datax );
	DB::Delete("outbox_mail_mailchimp", $datax );
	DB::Delete("outbox_telegram", $datax );
	DB::Delete("outbox_whatsapp", $datax );


	$data = array();
  $data["group_id"] = $values[group_id];
  $rs = DB::Select("group_member", $data );

  while( $record = $rs->fetchAssoc() )
  {
    $mmid = $record["member_id"];
    $gmid = $record["group_member_id"];
    $agendaType = $values["agenda_type_id"];
    $rs1 = DB::Query("select member_id from group_member_agenda_subscriber
    where agenda_type_id = '$agendaType' AND member_id = '$mmid'");
    $dataAgendaType = $rs1->fetchAssoc();
    if($dataAgendaType)
    {
      $data2 = array();
      $data2["group_member_id"] = $gmid;
      $data2["member_id"] = $mmid;
      $data2["group_agenda_id"] = $values['group_agenda_id'];
      $tgl = $values["loop_value"];
      $repeat = $values["repeat"];
      if($repeat == 0)
      {
        
        $data4 = array();
        $data4["member_id"] = $mmid;
        $data4["id_group_agenda"] = $values["group_agenda_id"];
        $data4["date_send"] = $values['loop_value'];

        $data3 = array();
        $data3["out_msg"] = $values["message_content"];
        $data3["type"] = "msg";
        $data3["flag"] = 1;
        $data3["group_member_id"] = $gmid;
        $data3["member_id"] = $mmid;
        $data3["group_id"] = $values["group_id"];
        $data3["group_agenda_id"] = $values["group_agenda_id"];

        $data31 = array();
        $data31["out_msg"] = $values["attachment"];
        $data31["type"] = "file";
        $data31["flag"] = 1;
        $data31["group_member_id"] = $gmid;
        $data31["member_id"] = $mmid;
        $data31["group_id"] = $values["group_id"];
        $data31["group_agenda_id"] = $values["group_agenda_id"];
				 if($values['loop_id'] == '2')
					{
						$data3["tgl"] = NOW();
						$data31["tgl"] = NOW();
					}
					else 
					{
						$data3["tgl"] = $tgl;
						$data31["tgl"] = $tgl;
					}

        $rs2 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 1");
        $dataChannelTele=$rs2->fetchAssoc();
        if($dataChannelTele)
        {
          $data3["chat_id"] = $dataChannelTele["chat_id"];
          $data31["chat_id"] = $dataChannelTele["chat_id"];
          DB::Insert("outbox_telegram", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_telegram", $data31 );
						}

        }

        $rs3 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 2");
        $dataChannelAws=$rs3->fetchAssoc();
        if($dataChannelAws)
        {
          $data3["chat_id"] = $dataChannelAws["chat_id"];
          $data31["chat_id"] = $dataChannelAws["chat_id"];
          DB::Insert("outbox_mail_aws", $data3 );
          DB::Insert("outbox_mail_alibaba", $data3 );
          DB::Insert("outbox_mail_mailchimp", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_mail_aws", $data31 );
							DB::Insert("outbox_mail_alibaba", $data31 );
							DB::Insert("outbox_mail_mailchimp", $data31 );
						}
		
        }

        $rs4 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 3");
        $dataChannelWa=$rs4->fetchAssoc();
        if($dataChannelWa)
        {
          $data3["chat_id"] = $dataChannelWa["chat_id"];
          $data31["chat_id"] = $dataChannelWa["chat_id"];
          DB::Insert("outbox_whatsapp", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_whatsapp", $data31 );
						}
        }


        $rs5 = DB::Query("select chat_id from personal_channel
        where member_id = '$mmid' AND channel_id = 4");
        $dataChannelLine=$rs5->fetchAssoc();
        if($dataChannelLine)
        {
          $data3["chat_id"] = $dataChannelLine["chat_id"];
          $data31["chat_id"] = $dataChannelLine["chat_id"];
          DB::Insert("outbox_line", $data3 );
						if($values['attachment']){
							DB::Insert("outbox_line", $data31 );
						}
        }
      }
      else
      {
        $data3 = array();
        $i = 0;
        while($i <= $repeat)
	      {
          $rep = $values["repeat_type"];
          if($rep == "bydate")
          {
						$data1 = array();
						$data1["out_msg"] = $values["message_content"];
						$data1["type"] = "msg";
						$data1["flag"] = 1;
					  $data1["group_member_id"] = $gmid;
					  $data1["member_id"] = $mmid;
					  $data1["group_id"] = $values["group_id"];
					  $data1["group_agenda_id"] = $values["group_agenda_id"];

						$data11 = array();
						$data11["out_msg"] = $values["attachment"];
						$data11["type"] = "file";
						$data11["flag"] = 1;
					  $data11["group_member_id"] = $gmid;
					  $data11["member_id"] = $mmid;
					  $data11["group_id"] = $values["group_id"];
					  $data11["group_agenda_id"] = $values["group_agenda_id"];

						$data2 = array();
						$data4 = array();
						$data4["member_id"] = $mmid;
						$data4["id_group_agenda"] = $values["group_agenda_id"];
						$data4["date_send"] = $tgl;
            if($i == 0)
            {
              
              $data1["tgl"] = $tgl;
              $rs1 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 1");
              $dataChannelTele=$rs1->fetchAssoc();
              if($dataChannelTele)
              {
               $data1["chat_id"] = $dataChannelTele["chat_id"];
               $data11["chat_id"] = $dataChannelTele["chat_id"];
               DB::Insert("outbox_telegram", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_telegram", $data11 );
								}
              }
      
              $rs2 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 2");
              $dataChannelAws=$rs2->fetchAssoc();
              if($dataChannelAws)
              {
               $data1["chat_id"] = $dataChannelAws["chat_id"];
               $data11["chat_id"] = $dataChannelAws["chat_id"];
               DB::Insert("outbox_mail_alibaba", $data1 );
               DB::Insert("outbox_mail_aws", $data1 );
               DB::Insert("outbox_mail_mailchimp", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_mail_alibaba", $data11 );
									DB::Insert("outbox_mail_aws", $data11 );
									DB::Insert("outbox_mail_mailchimp", $data11 );
								}
              }
      
              $rs3 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 3");
              $dataChannelWa=$rs3->fetchAssoc();
              if($dataChannelWa)
              {
               $data1["chat_id"] = $dataChannelWa["chat_id"];
               $data11["chat_id"] = $dataChannelWa["chat_id"];
               DB::Insert("outbox_whatsapp", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_whatsapp", $data11 );
								}
              }
      
              $rs4 = DB::Query("select chat_id from personal_channel
              where member_id = '$mmid' AND channel_id = 4");
              $dataChannelLine=$rs4->fetchAssoc();
              if($dataChannelLine)
              {
               $data1["chat_id"] = $dataChannelLine["chat_id"];
               $data11["chat_id"] = $dataChannelLine["chat_id"];
               DB::Insert("outbox_line", $data1 );
								if($values['attachment']){
									DB::Insert("outbox_line", $data11 );
								}
              }


								DB::Insert("group_agenda_general_logs", $data4 );
            }
            else
            {
              //$data2["group_agenda_id"] = $idm;
              //$data2["dodate"] = now();
              //DB::Insert("group_agenda_repeat_date", $data2 );
								//DB::Insert("group_agenda_general_logs", $data4 );
            }
          }
          else
          {
            if($i == 0)
            {
              $data3["tgl"] = $tgl;
              $data31["tgl"] = $tgl;
								$tgl3 = $tgl;
            }else if($i > 0)
            {
              
              if($values["repeat_type"] == "daily")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 day' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "weekly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 week' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "monthly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 month' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }else if($rep == "yearly")
              {
                $tgl2 = $data3["tgl"];
                $tgl3 = date('Y-m-d H:i:s', strtotime($tgl2 . ' +1 year' ));
                $data3["tgl"] = $tgl3;
                $data31["tgl"] = $tgl3;
              }
            }
            $data4 = array();
            $data4["member_id"] = $mmid;
            $data4["id_group_agenda"] = $values["group_agenda_id"];
            $data4["date_send"] = $tgl3;
            
            
            $data3["out_msg"] = $values["message_content"];
            $data3["type"] = "msg";
            $data3["flag"] = 1;
					  $data3["group_member_id"] = $gmid;
					  $data3["member_id"] = $mmid;
					  $data3["group_id"] = $values["group_id"];
					  $data3["group_agenda_id"] = $values["group_agenda_id"];

            $data31["out_msg"] = $values["attachment"];
            $data31["type"] = "file";
            $data31["flag"] = 1;
					  $data31["group_member_id"] = $gmid;
					  $data31["member_id"] = $mmid;
					  $data31["group_id"] = $values["group_id"];
					  $data31["group_agenda_id"] = $values["group_agenda_id"];

            $rs2 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 1");
            $dataChannelTele=$rs2->fetchAssoc();
            if($dataChannelTele)
            {
              $data3["chat_id"] = $dataChannelTele["chat_id"];
              $data31["chat_id"] = $dataChannelTele["chat_id"];
              DB::Insert("outbox_telegram", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_telegram", $data31 );
								}

            }

            $rs3 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 2");
            $dataChannelAws=$rs3->fetchAssoc();
            if($dataChannelAws)
            {
              $data3["chat_id"] = $dataChannelAws["chat_id"];
              $data31["chat_id"] = $dataChannelAws["chat_id"];
              DB::Insert("outbox_mail_alibaba", $data3 );
              DB::Insert("outbox_mail_aws", $data3 );
              DB::Insert("outbox_mail_mailchimp", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_mail_alibaba", $data31 );
									DB::Insert("outbox_mail_aws", $data31 );
									DB::Insert("outbox_mail_mailchimp", $data31 );
								}
            }

            $rs4 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 3");
            $dataChannelWa=$rs4->fetchAssoc();
            if($dataChannelWa)
            {
              $data3["chat_id"] = $dataChannelWa["chat_id"];
              $data31["chat_id"] = $dataChannelWa["chat_id"];
              DB::Insert("outbox_whatsapp", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_whatsapp", $data31 );
								}
            }


            $rs5 = DB::Query("select chat_id from personal_channel
            where member_id = '$mmid' AND channel_id = 4");
            $dataChannelLine=$rs5->fetchAssoc();
            if($dataChannelLine)
            {
              $data3["chat_id"] = $dataChannelLine["chat_id"];
              $data31["chat_id"] = $dataChannelLine["chat_id"];
              DB::Insert("outbox_line", $data3 );
								if($values['attachment']){
									DB::Insert("outbox_line", $data31 );
								}
            }

          }
					$i += 1;
        }
      }
    }
  }
}else{
	$data3 = array();
	if($values['message_general']=="General"){
		$data3["out_msg"]  = $values['message_content'];	
	}
	if($values['message_general']!="Private" && ($values['repeat'] == 0 || $values['repeat'] == null)){
		$data3["tgl"] = $values['loop_value'];
	}

	if($values['message_general']=="Private"){
		$data3["tgl"] = $values['send_date'];
	}

	$keyvalues = array();
	$keyvalues["group_agenda_id"] = $values['group_agenda_id'];
	$keyvalues["flag"] = '1';
	$keyvalues["type"] = 'msg';

	
	DB::Update("outbox_telegram", $data3, $keyvalues );
	DB::Update("outbox_mail_alibaba", $data3, $keyvalues );
	DB::Update("outbox_mail_aws", $data3, $keyvalues );
	DB::Update("outbox_mail_mailchimp", $data3, $keyvalues );
	DB::Update("outbox_whatsapp", $data3, $keyvalues );
	DB::Update("outbox_line", $data3, $keyvalues );


	$data31 = array();
	$data31["out_msg"]  = $values['attachment'];
	if($values['repeat'] == 0 || $values['repeat'] == null){
		$data31["tgl"] = $values['loop_value'];
	}

	if(!$oldvalues['attachment'] && $values['attachment']){
		$data311["flag"]  = "1";
		$data311["type"] = 'file';
		$data311["member_agenda_id"] = $values['member_agenda_id'];
		$data311["member_id"] = $values['member_id'];

		$data = array();
		$data["group_agenda_id"] = $values['group_agenda_id'];
		$data["flag"]  = "1";
		$rs4 = DB::Select("outbox_mail_aws", $data );
		while( $record4 = $rs4->fetchAssoc() )
		{
			$data4 = array();
			$data4["out_msg"] = $values["attachment"];
			$data4["chat_id"] = $record4["chat_id"];
			$data4["type"] = 'file';
			$data4["flag"] = $record4["flag"];
			$data4["tgl"] = $record4["tgl"];
			$data4["group_agenda_id"] = $record4["group_agenda_id"];
			$data4["group_agenda_private_id"] = $record4["group_agenda_private_id"];
			$data4["member_agenda_id"] = $record4["member_agenda_id"];
			$data4["group_id"] = $record4["group_id"];
			$data4["group_member_id"] = $record4["group_member_id"];
			$data4["member_id"] = $record4["member_id"];
			$data4["id_group_repeat"] = $record4["id_group_repeat"];

			$data5 = array();
			$data5["member_id"] = $record4["member_id"];
			$data5["chat_id"]  = $record4["chat_id"];
			$rs5 = DB::Select("personal_channel", $data5 );
			while( $record5 = $rs5->fetchAssoc() )
			{
				 $channel_id = $record5["channel_id"];
			}

			if($channel_id==1){
				DB::Insert("outbox_telegram", $data4 );
			}else if($channel_id==2){
				DB::Insert("outbox_mail_alibaba", $data4 );
				DB::Insert("outbox_mail_aws", $data4 );
				DB::Insert("outbox_mail_mailchimp", $data4 );
			}else if($channel_id==3){
				DB::Insert("outbox_whatsapp", $data4 );
			}else if($channel_id==4){
				DB::Insert("outbox_line", $data4 );
			}
		}
	}

	$keyvalues1 = array();
	$keyvalues1["group_agenda_id"] = $values['group_agenda_id'];
	$keyvalues1["flag"] = '1';
	$keyvalues1["type"] = 'file';

	DB::Update("outbox_telegram", $data31, $keyvalues1 );
	DB::Update("outbox_mail_alibaba", $data31, $keyvalues1 );
	DB::Update("outbox_mail_aws", $data31, $keyvalues1 );
	DB::Update("outbox_mail_mailchimp", $data31, $keyvalues1 );
	DB::Update("outbox_whatsapp", $data31, $keyvalues1 );
	DB::Update("outbox_line", $data31, $keyvalues1 );

	if($oldvalues['attachment'] && !$values['attachment']){
		DB::Delete("outbox_telegram", $keyvalues1 );
		DB::Delete("outbox_mail_alibaba", $keyvalues1 );
		DB::Delete("outbox_mail_aws", $keyvalues1 );
		DB::Delete("outbox_mail_mailchimp", $keyvalues1 );
		DB::Delete("outbox_whatsapp", $keyvalues1 );
		DB::Delete("outbox_line", $keyvalues1 );
	}
}

  
if($values['message_general']=='Private' && $values['message_general'] != $oldvalues['message_general']){
	header("Location: group_agenda_private_import.php");
	exit();
}

if($values['repeat_type']!='bydate'){
	header("Location: group_agenda_list.php");
	exit();
}
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
