<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_agenda_private  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


		$this->events["AfterImport"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$rs = DB::Query("select chat_id from personal_channel
where member_id = '$values[id_member]' AND channel_id = 1");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $values["message_content"];
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = $values["date_send"];
	DB::Insert("outbox_telegram", $data );
}
else
{
	// if dont exist do something else
}

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$values[id_member]' AND channel_id = 2");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $values["message_content"];
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = $values["date_send"];
	DB::Insert("outbox_mail_aws", $data );
}
else
{
	// if dont exist do something else
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After Import Finished
function AfterImport($count, $skipCount, &$pageObject)
{

		$sql = "SELECT * FROM group_agenda WHERE group_agenda_id=(SELECT MAX(group_agenda_id) FROM group_agenda)";
$preparedSQL = DB::PrepareSQL( $sql );
$rs = DB::Query( $preparedSQL );
while( $record = $rs->fetchAssoc() )
{
    $group_agenda_id = $record["group_agenda_id"];
		$group_id = $record["group_id"];
		$send_date = $record["send_date"];
		$attachment = $record["attachment"];
}

$data = array();
$keyvalues = array();
$data["id_group_agenda"] = $group_agenda_id;
$data["group_id"] = $group_id;
$keyvalues["id_group_agenda"] = NULL;
DB::Update("group_agenda_private", $data , $keyvalues);

$data = array();
$keyvalues = array();
$data["date_send"] = $send_date;
$data["attachment"] = $attachment;
$keyvalues["id_group_agenda"] = group_agenda_id;
DB::Update("group_agenda_private", $data , $keyvalues);

$sql = "SELECT * FROM group_agenda WHERE group_agenda_id=(SELECT MAX(group_agenda_id) FROM group_agenda)";
$preparedSQL = DB::PrepareSQL( $sql );
$rs = DB::Query( $preparedSQL );
while( $record = $rs->fetchAssoc() )
{
    $group_agenda_id = $record["group_agenda_id"];
		$send_date = $record["send_date"];
		$attachment = $record["attachment"];
}

$data = array();
$keyvalues = array();
$data["date_send"] = $send_date;
$data["attachment"] = $attachment;
$keyvalues["id_group_agenda"] = $group_agenda_id;
DB::Update("group_agenda_private", $data , $keyvalues);


$data1 = array();
$data1["id_group_agenda"] = $group_agenda_id;
$rs = DB::Select("group_agenda_private", $data1 );
while( $record = $rs->fetchAssoc() )
{
    $data2 = array();
		$data2["member_id"] = $record["id_member"];
		$rs1 = DB::Select("personal_channel", $data2 );
		while( $record2 = $rs1->fetchAssoc() )
		{
				
				$data5 = array();
				$data5["member_id"] = $record["id_member"];
				$data5["group_id"] = $group_id;
				$rs5 = DB::Select("group_member", $data5 );
				while( $record5 = $rs5->fetchAssoc() )
				{
					$group_member_id = $record5["group_member_id"];
				}

				$data3 = array();
				$data3["chat_id"] = $record2["chat_id"];
				$data3["out_msg"]  = $record["message_content"];
				$data3["flag"] = '1';
				$data3["tgl"] = $record["date_send"];
        $data3["group_member_id"] = $group_member_id;
        $data3["member_id"] = $record["id_member"];
        $data3["group_agenda_private_id"] = $record["group_agenda_private_id"];
        $data3["group_id"] = $group_id;
        $data3["group_agenda_id"] = $group_agenda_id;

				$data31 = array();
				$data31["chat_id"] = $record2["chat_id"];
				$data31["out_msg"]  = $record["attachment"];
				$data31["flag"] = '1';
				$data31["type"] = 'file';
				$data31["tgl"] = $record["date_send"];
        $data31["group_member_id"] = $group_member_id;
        $data31["member_id"] = $record["id_member"];
        $data31["group_agenda_private_id"] = $record["group_agenda_private_id"];
        $data31["group_id"] = $group_id;
        $data31["group_agenda_id"] = $group_agenda_id;

				if($record2["channel_id"]==1)
				{
					DB::Insert("outbox_telegram", $data3 );
					if($record["attachment"]){
						DB::Insert("outbox_telegram", $data31 );
					}
				}

				else if($record2["channel_id"]==2)
				{
					DB::Insert("outbox_mail_alibaba", $data3 );
					DB::Insert("outbox_mail_aws", $data3 );
					DB::Insert("outbox_mail_mailchimp", $data3 );
					if($record["attachment"]){
						DB::Insert("outbox_mail_alibaba", $data31 );
						DB::Insert("outbox_mail_aws", $data31 );
						DB::Insert("outbox_mail_mailchimp", $data31 );
					}
				}

				else if($record2["channel_id"]==3)
				{
					DB::Insert("outbox_whatsapp", $data3 );
					if($record["attachment"]){
						DB::Insert("outbox_whatsapp", $data31 );
					}
				}

				else if($record2["channel_id"]==4)
				{
					DB::Insert("outbox_line", $data3 );
					if($record["attachment"]){
						DB::Insert("outbox_line", $data31 );
					}
				}
		}
}


$datax = array();
$datax["id_group_agenda"] = $group_agenda_id;
$rs = DB::Select("group_agenda_private", $datax );
while( $recordx = $rs->fetchAssoc() )
{
	$member_id = $recordx["id_member"];
	$group_agenda_private_id = $recordx["group_agenda_private_id"];

	$parts = explode('"', $attachment);

	$length = count($parts);

	foreach ($parts as $part) {
	  if (strpos($part, 'files\/'.$member_id.'_') !== false) {
			 $member_attach = str_replace("\/","/",$part);
				break;
		}
	}

	if($member_attach){
		$datay = array();
		$keyvaluesy = array();
		$datay["attachment"] = $member_attach;
		$keyvaluesy["group_agenda_private_id"] = $group_agenda_private_id;
		DB::Update("group_agenda_private", $datay, $keyvaluesy );

		$datay1 = array();
		$datay1["out_msg"] = $member_attach;
		$keyvaluesy["type"] = "file";
		DB::Update("outbox_line", $datay1, $keyvaluesy );
		DB::Update("outbox_mail_alibaba", $datay1, $keyvaluesy );
		DB::Update("outbox_mail_aws", $datay1, $keyvaluesy );
		DB::Update("outbox_mail_mailchimp", $datay1, $keyvaluesy );
		DB::Update("outbox_telegram", $datay1, $keyvaluesy );
		DB::Update("outbox_whatsapp", $datay1, $keyvaluesy );
	}
}

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterImport

		
		
		
		
		
		
		
		
		
		



}
?>
