<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_personal_channel  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowEdit"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["AfterDelete"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, &$pageObject)
{

		$pageObject->hideItem("integrated_edit_field1");

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$data = array();
$keyvalues = array();
$data["chat_id"] = $values['chat_id'];
$keyvalues["flag"]  = "1";
$keyvalues["member_id"] = $values['member_id'];


if($values['channel_id'] == 1){
	DB::Update("outbox_telegram", $data, $keyvalues );
}else if($values['channel_id'] == 2){
	DB::Update("outbox_mail_alibaba", $data, $keyvalues );
	DB::Update("outbox_mail_aws", $data, $keyvalues );
	DB::Update("outbox_mail_mailchimp", $data, $keyvalues );
}else if($values['channel_id'] == 3){
	DB::Update("outbox_whatsapp", $data, $keyvalues );
}else if($values['channel_id'] == 4){
	DB::Update("outbox_line", $data, $keyvalues );
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, &$pageObject)
{

		$data = array();
$data["member_id"] = $deleted_values['member_id'];
$data["chat_id"] = $deleted_values['chat_id'];
$data["flag"] = "1";
DB::Delete("outbox_line", $data );
DB::Delete("outbox_whatsapp", $data );
DB::Delete("outbox_telegram", $data );
DB::Delete("outbox_mail_mailchimp", $data );
DB::Delete("outbox_mail_aws", $data );
DB::Delete("outbox_mail_alibaba", $data );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
